name: Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        git clone --depth=1 https://github.com/KazuDante89/android_kernel_ghost_lisa.git -b Proton_R0.3 "$(pwd)"/Kernel
        cd "$(pwd)"/Kernel
        chmod a+x CompileKernel.sh
        bash CompileKernel.sh
